apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName | quote }}
spec:
  defaultBackend:
    service:
      name: {{ .Values.frontend.name }}-service
      port:
        number: {{ .Values.frontend.port.service }}
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-service
                port:
                  number: {{ .Values.backend.port.service }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}-service
                port:
                  number: {{ .Values.frontend.port.service }}
