apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.namespace }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: wanderlust
    meta.helm.sh/release-namespace: {{ .Values.global.namespace }}