apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongo.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mongo.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}