apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.redis.name }}
  ports:
    - port: {{ .Values.redis.port.service }}
      targetPort: {{ .Values.redis.port.container }}
      protocol: TCP