apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.port.service }}
      targetPort: {{ .Values.backend.port.container }}
      protocol: TCP